# Use root/example as user/password credentials
version: '3.1'

services:
  nest:
    image: nest-server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:api.welab22.com"
