# Use root/example as user/password credentials
version: '3.1'

services:
  nest:
    image: nest-server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 33572:3000
    links:
      - db
    depends_on:
      - db
    networks:
      - project-network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pa8-project
      MYSQL_DATABASE: pa8-db
    networks:
      - project-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 33571:8080
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
