# Use root/example as user/password credentials
version: '3.1'

services:
  nest:
    image: nest-server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      NODE_ENV: development
    networks:
      - project-network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    networks:
      - project-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
