# Use root/example as user/password credentials
version: '3.5'

services:
  nest:
    image: nest-server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    #ports:
    # - 3000:3000
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:api.welab22.com"
    links:
      - db
    depends_on:
      - db
    networks:
      - dockerdemo_default

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pa8-project
      MYSQL_DATABASE: pa8-db
    networks:
      - dockerdemo_default:
          ipv4_address: 172.20.0.8

  adminer:
    image: adminer
    restart: always
    #ports:
    #  - 8080:8080
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:adminer.welab22.com"
    networks:
      - dockerdemo_default

networks:
  dockerdemo_default:
    name: dockerdemo_default
